### ISSUE TITLE
Unable to compile code using boost/process.hpp

### ISSUE THREAD

**Issue by tim-wilkins** [boostorg/boost#350]
The following code fails to build in Visual Studio 2019 (16.4.1) using boost 1.72, debug x64 build.

#include "boost/process.hpp"

void out(const char* d);
int main()
{
    char data[100000];
    memset(data, 0, sizeof data);

    boost::asio::io_context ios;

    boost::process::child c("dir", boost::process::std_out > boost::asio::buffer(data), boost::process::std_err > boost::process::null, ios);

    ios.run();
    int result = c.exit_code();
    out(data);
}
#include <iostream>
void out(const char* d)
{
    std::cout << d;
}

Errors:

C:\boost\boost_1_72_0\boost\asio\impl\read.hpp(460,39): error C2039: 'executor_type': is not a member of 'boost::process::detail::windows::async_pipe'
C:\boost\boost_1_72_0\boost\asio\impl\read.hpp(460,1): error C3646: 'executor_type': unknown override specifier
C:\boost\boost_1_72_0\boost\asio\impl\read.hpp(460,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

Adding
#include "boost/asio.hpp"
didn't help.
