### ISSUE TITLE
boost::parser compilation error on mac with boost 1.88

### ISSUE THREAD

**Issue by SilkeSchomann** [boostorg/boost#1073]
view_adaptor.hpp (boost::parser) does not compile on a mac with clang 18.1.8 and boost 1.88:

```
/include/boost/parser/detail/stl_interfaces/view_adaptor.hpp:199:35: error: no template named 'range_adaptor_closure' in namespace 'std::ranges'; did you mean 'std::__range_adaptor_closure'?
199 |     using range_adaptor_closure = std::ranges::range_adaptor_closure<D>;
    |                                                          ^~~~~~~~~~~~~
/bin/../include/c++/v1/__ranges/range_adaptor.h:58:8: note: 'std::__range_adaptor_closure' declared here
58 | struct __range_adaptor_closure {
   |            ^
1 error generated.
```

**Comment by mclow** [comment]
Can you try this with the Boost 1.89 release candidate, please?

https://archives.boost.io/release/1.89.0/source/
